language: generic
before_install:
    - cd scripts/install-vagrant;./install-vagrant-linux-ubuntu.sh;
install:
    - sudo -E su $USER -c 'cd $HOME/stackinabox/vagrant/;./build.sh'
script:
    - sudo -E su $USER -c 'cd $HOME/stackinabox/vagrant/;./package.sh'
branches:
    only:
        - master
addons:
    artifacts: true
    s3_region: "us-east-1"
sudo: required
dist: trusty