language: generic
before_install:
    - scripts/install-vagrant/install-vagrant-linux-ubuntu.sh;
    - sudo usermod -a -G vboxusers $USER
install:
    - sudo -E su $USER -c 'vagrant/build.sh'
script:
    - sudo -E su $USER -c 'vagrant/package.sh'
branches:
    only:
        - master
addons:
    artifacts: true
    s3_region: "us-east-1"
sudo: required
dist: trusty
